### ISSUE TITLE
Improve Timer picker style configurability

### ISSUE THREAD

**Issue by kwangure** [kwangure/strawberry#20]
There is currently no way to configure Time-input specific `background` and `border-radius`. The only way to do it is through `:global()`.

A refinement to the current API would look something like:

```css
.berry-input-time {
    --br-input-time-icon-size: 21px;
    --br-input-time-number-input-background-color: var(--br-primary-light);
    --br-input-time-number-input-border-radius: var(--br-border-radius);
}
```
